### ISSUE TITLE
i try convert but my json file is blank

### ISSUE THREAD

**Issue by shinnobi** [pwcazenave/netcdf2json#3]
i try modify your code 
![anh1](https://user-images.githubusercontent.com/21121259/66998021-b379b200-f0fd-11e9-84fd-8ac3ac124986.png)

but when i run your code it still blank

please help me thanks

**Comment by Gxmg** [comment]
> i try modify your code
> ![anh1](https://user-images.githubusercontent.com/21121259/66998021-b379b200-f0fd-11e9-84fd-8ac3ac124986.png)
> 
> but when i run your code it still blank
> 
> please help me thanks

I also encountered the same problem, did you solve it?
