### ISSUE TITLE
pleas  tell me how to format the data aplly to earth,thanks.

### ISSUE THREAD

**Issue by Gxmg** [pwcazenave/netcdf2json#4]
Hello, how do I convert the data format of netcdf to the format required by earth-null? I tried to use ncdump-json, but there is no header and other attributes. What if I want to apply data to earth-null?

**Comment by Gxmg** [comment]
**xhonco_???????????U.nc** and **xhonco_???????????V.nc** and **xhonco_???????????P.nc**, are these three files the same file?

**Comment by pwcazenave** [comment]
You might find the ncdump-json tool more useful as I haven't really tested my Python version.

https://github.com/jllodra/ncdump-json
